version: "3"
services:
  db:
    container_name: isucon-log-db
    build: ./db
    volumes:
      - ./db/mount:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database_development